apiVersion: v1
kind: Secret
metadata:
  name: flask-secret
type: Opaque
data:
  # Replace below value with base64 of your SECRET_KEY
  # Example: echo -n 'super-secret' | base64
  SECRET_KEY: cmFuZG9tLXNlY3JldA==

  # MariaDB connection string (base64). This will override ConfigMap's SQLALCHEMY_DATABASE_URI.
  # Example (edit values):
  #   echo -n 'mysql+pymysql://appuser:apppass@mariadb:3306/products?charset=utf8mb4' | base64
  # SQLALCHEMY_DATABASE_URI: bXlzcWwrcHlteXNxbDovL2FwcHVzZXI6YXBwcGFzc0BtYXJpYWRiOjMzMDYvcHJvZHVjdHM/Y2hhcnNldD11dGY4bWI0
